# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grol < Formula
  desc "Go Repl Open Language: simple, small but powerful interpreted language in Go"
  homepage "https://grol.io/"
  version "0.22.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/grol-io/grol/releases/download/v0.22.2/grol_0.22.2_darwin_amd64.zip"
      sha256 "b7cdca78c44963d7de1f7a03f33940df9ddadd0f25dda659fbf34a2eae34a64d"

      def install
        bin.install "grol"
      end
    end
    on_arm do
      url "https://github.com/grol-io/grol/releases/download/v0.22.2/grol_0.22.2_darwin_arm64.zip"
      sha256 "6ae57ec9677029243182808b183d0af33b417a456e357818d68e8b50f8f377c8"

      def install
        bin.install "grol"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/grol-io/grol/releases/download/v0.22.2/grol_0.22.2_linux_amd64.tar.gz"
        sha256 "244215d4e57e627828a582aff61512ac7f9ff7d6bfc39627dfed6a9e7de8b1c4"

        def install
          bin.install "grol"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/grol-io/grol/releases/download/v0.22.2/grol_0.22.2_linux_arm64.tar.gz"
        sha256 "373cd5406d8a8ea6eb8aafa7672d5ac485ded27280e90bb61577e2ca0082fddd"

        def install
          bin.install "grol"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grol -version")
  end
end
