# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grol < Formula
  desc "Go Repl Open Language: simple, small but powerful interpreted language in Go"
  homepage "https://grol.io/"
  version "0.54.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/grol-io/grol/releases/download/v0.54.0/grol_0.54.0_darwin_amd64.zip"
      sha256 "959c24af9b197d9a236ee4d4d80ed4f7130d5b281c94c42d7621cd1be4bfeb50"

      def install
        bin.install "grol"
      end
    end
    on_arm do
      url "https://github.com/grol-io/grol/releases/download/v0.54.0/grol_0.54.0_darwin_arm64.zip"
      sha256 "b1c51363e6ee10f04fd9713068a73aae04e5e9b3fb4ac0e24f61607cdfb81f8a"

      def install
        bin.install "grol"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/grol-io/grol/releases/download/v0.54.0/grol_0.54.0_linux_amd64.tar.gz"
        sha256 "d2595b63a49a7889fea50821bfa05dbdbe7835efd01d822a9a4b535adbb879d7"

        def install
          bin.install "grol"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/grol-io/grol/releases/download/v0.54.0/grol_0.54.0_linux_arm64.tar.gz"
        sha256 "a41a8fcf824ffc6914f14f3ae196cfc56b4f2607168d20e547d3748015ab8ce2"

        def install
          bin.install "grol"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grol -version")
  end
end
