# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vm < Formula
  desc "Go Repl Open Language: simple, small but powerful VM language in Go"
  homepage "https://grol.io/"
  version "0.30.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grol-io/vm/releases/download/v0.30.0/vm_0.30.0_darwin_amd64.zip"
      sha256 "08da62939df9b1d8cc617dfd00acb0fabc3607a68f41bc10fb7d53369125ffde"

      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grol-io/vm/releases/download/v0.30.0/vm_0.30.0_darwin_arm64.zip"
      sha256 "00e954f5a12553b172c25fe89e77b7d0040f84cd358e9dc982b6ec757d688601"

      def install
        bin.install "vm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.30.0/vm_0.30.0_linux_amd64.tar.gz"
      sha256 "be41ba1a7ebc1c8a385204b41c3427d28f92b9e5f37de811e4aec29a44f60053"
      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.30.0/vm_0.30.0_linux_arm64.tar.gz"
      sha256 "b2ed91f2b6ed01738cdd53653d56b5e89dc322e60380e0f21436a9323503df8c"
      def install
        bin.install "vm"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vm -version")
  end
end
