# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vm < Formula
  desc "Go Repl Open Language: simple, small but powerful VM language in Go"
  homepage "https://grol.io/"
  version "0.33.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grol-io/vm/releases/download/v0.33.0/vm_0.33.0_darwin_amd64.zip"
      sha256 "4ef1d2759490b13e782fd2bb894562b50f641a32828795bae0792b78f6e2347e"

      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grol-io/vm/releases/download/v0.33.0/vm_0.33.0_darwin_arm64.zip"
      sha256 "3bd31263b6ae9e0d88d9bc767af529534940bb8b9f322ab02dd5e3060e07be31"

      def install
        bin.install "vm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.33.0/vm_0.33.0_linux_amd64.tar.gz"
      sha256 "884ff1acdb92a2f4d41b1c6e93ed18df7d00174737bef2ae86746c6566967119"
      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.33.0/vm_0.33.0_linux_arm64.tar.gz"
      sha256 "ba6ed171ad0b538f60f6662be8b4d772ebc0c66f3016859a719b8593ee4ca4f8"
      def install
        bin.install "vm"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vm -version")
  end
end
