# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vm < Formula
  desc "Go Repl Open Language: simple, small but powerful VM language in Go"
  homepage "https://grol.io/"
  version "0.24.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grol-io/vm/releases/download/v0.24.0/vm_0.24.0_darwin_amd64.zip"
      sha256 "08f3fe512176217e40f44cdb71889067030b6fdf49eaf9a978483df1bf3f25fc"

      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grol-io/vm/releases/download/v0.24.0/vm_0.24.0_darwin_arm64.zip"
      sha256 "eff9bb4c29127979778983bb83221564fef45aa21e64049e61d2406a493f9d5e"

      def install
        bin.install "vm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.24.0/vm_0.24.0_linux_amd64.tar.gz"
      sha256 "113768d44b94001c1d5fe2df54538605d4b1527fa0d940c7837ebc04c20ab0fb"
      def install
        bin.install "vm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grol-io/vm/releases/download/v0.24.0/vm_0.24.0_linux_arm64.tar.gz"
      sha256 "06cf74e1f429022e90bdaef994e0e17fb2820bb18c5f66540f710ed14a683b18"
      def install
        bin.install "vm"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vm -version")
  end
end
